# -*- coding: utf-8 -*-
"""synent_task3_EDA_Anas Solanki.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSqFcScIjeSXWjH8XJIKVG2pUaBVGSW4
"""

# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

import os
print(os.listdir())

# Load Data
df = pd.read_csv("netflix_titles.csv")

df.head()

# Data Overview

print("Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())

df.info()

print("\nMissing Values:\n")
print(df.isnull().sum())

# Basic Cleaning

df = df.copy()

# Fill missing values
df['country'] = df['country'].fillna("Unknown")
df['rating'] = df['rating'].fillna("Unknown")

# Convert date
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Extract year
df['year_added'] = df['date_added'].dt.year

# Content Type Distribution

plt.figure()

df['type'].value_counts().plot(kind='bar')

plt.title("Movies vs TV Shows")
plt.xlabel("Type")
plt.ylabel("Count")

plt.show()

# Trend Over Years

plt.figure()

df['year_added'].value_counts().sort_index().plot()

plt.title("Content Added Over Years")
plt.xlabel("Year")
plt.ylabel("Count")

plt.show()

# Top Countries

top_countries = df['country'].value_counts().head(10)

plt.figure()

top_countries.plot(kind='bar')

plt.title("Top 10 Countries Producing Content")
plt.xlabel("Country")
plt.ylabel("Count")

plt.show()

# Genre Analysis

# Split genres
df['listed_in'] = df['listed_in'].str.split(',')

# Explode
genre_df = df.explode('listed_in')

top_genres = genre_df['listed_in'].value_counts().head(10)

plt.figure()

top_genres.plot(kind='bar')

plt.title("Top Genres on Netflix")
plt.xlabel("Genre")
plt.ylabel("Count")

plt.show()